---
title: |
 | Tarefa 1 - Análise Multivariada
 | *Análise dos lanches da empresa McDonalds*
subtitle: | 
 | Docente: Dr. Afrânio vieira
 | Departamento: Estatística e Experimentação Agronômica - USP
author: 
  name: "Welinton Yoshio Hirai"
  email: 'wyhirai@usp.br'
date: "02/04/2020"
output: pdf_document
---

```{r setup, include=F}
rm(list=ls(all=T));options(device = 'windows');cat("\f")

#opções de chunck
knitr::opts_chunk$set(
  fig.align = 'center',
  fig.width = 10,
  fig.height = 6,
  dpi = 300
)

#pacotes utilizados
library(ggplot2) #gráficos
library(magrittr) #pipes
library(reshape2) #organização dos dados

link_github <- 'https://raw.githubusercontent.com/wyhirai/LCE5860_multivariate-analysis/master'
```

# Dados 
```{r data}
data_sand <- 
  link_github %>% 
  paste('/first_homework/data_sand.txt', sep = '') %>% 
  url() %>% 
  read.table(header = T, dec = ',')
```

# Análise Gráfica

## Unidimensional
```{r}
data_sand %>% 
  melt(id.vars = 'Sanduiches') %>% 
  ggplot(aes(y = value,
             fill = variable)) +
  geom_boxplot(col = 'black') +
  geom_violin(aes(x = 0), alpha = .2) +
  facet_wrap(facets = 'variable', scales = 'free') +
  stat_summary(aes(x = 0), fun.y = 'mean', geom = 'point',
               col = 'white', size = 2, pch = 15) +
  theme(legend.position = 'none') +
  xlab('') + ylab('') +
  coord_flip()
```

## Bidimensional
```{r}
pairs(data_sand[,-1], gap = 0)
```

```{r}
cor(data_sand[,-1], method = 'pearson') %>% 
  corrplot::corrplot(method = 'color',
                     type = 'upper', 
                     diag = F,
                     addCoef.col = 'black',
                     tl.col = 'black')
```

```{r}
ppcor::pcor(data_sand[,-1])$estimate %>% 
  corrplot::corrplot(method = 'color',
                     type = 'upper', 
                     diag = F,
                     addCoef.col = 'black',
                     tl.col = 'black')
```

## Tridimensional
```{r}
data_sand %$% 
  plot3D::scatter3D(x = carboidrato,
                    y = proteina,
                    z = valor_energ,
                    xlab = 'carboidrato',
                    ylab = 'proteina',
                    zlab = 'valor energético',
                    phi = 10,
                    theta = 30,
                    bty = 'g',
                    type = 'h',
                    ticktype = 'detailed',
                    pch = 20,
                    colvar = NULL)
```

```{r}
data_sand %>% 
  ggplot(aes(x = carboidrato,
             y = proteina,
             size = valor_energ)) +
  geom_point(aes(col = valor_energ))
```

## Múltiplos
```{r}
par(las = 2, mai = c(1.3, 0, 0, 0))
MASS::parcoord(data_sand[,-1],
               col = rep(c(1, 2, 3, 4, 5), each = 4),
               lty = rep(c(1, 2, 3, 4, 5), times = 4))
legend('topright',
       legend = data_sand$Sanduiches,
       cex = .8,
       col = rep(c(1, 2, 3, 4, 5), each = 4),
       lty = rep(c(1, 2, 3, 4, 5), times = 4))
```

```{r}
stars(data_sand[,-1], ncol = 6,
      labels = as.character(data_sand$Sanduiches),
      draw.segments = T,
      col.stars = T,
      cex = .7,
      key.loc = c(13, 1.9))
```

```{r}
data_sand[,-1] %>% 
  scale() %>%
  dist(diag = T, upper = T) %>% 
  as.matrix() %>% 
  melt() %>% 
  ggplot(aes(x = Var1,
             y = Var2,
             fill = value)) +
  geom_tile(colour = 'white') +
  scale_fill_gradient(low = "gray", high = "black") +
  xlab('') + ylab('') +
  scale_x_discrete(expand = c(0, 0),
                   limits = seq(1, 20, 1),
                   breaks = seq(1, 20, 1),
                   labels = data_sand$Sanduiches) +
  scale_y_discrete(expand = c(0, 0),
                   limits = seq(1, 20, 1),
                   breaks = seq(1, 20, 1),
                   labels = data_sand$Sanduiches) +
  theme(axis.text.x = element_text(angle = 90, hjust = 1))
```

